### ISSUE TITLE
no module named 'esp32_ulp.src_to_binary'

### ISSUE THREAD

**Issue by ouinouin** [Staars/berry-examples#1]
Hi, 
i m following the instructions on tasmota, i m running micropython under ubuntu but got some errors : 
```ouinouin@toshouin:~$ micropython 
MicroPython v1.17+ds-1.1ubuntu2 on 2022-03-10; linux version
Use Ctrl-D to exit, Ctrl-E for paste mode
>>> import esp32
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'esp32'
>>> import esp32_ulp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ouinouin/.micropython/lib/esp32_ulp/__init__.py", line 3, in <module>
  File "/home/ouinouin/.micropython/lib/esp32_ulp/preprocess.py", line 3, in <module>
  File "/home/ouinouin/.micropython/lib/esp32_ulp/definesdb.py", line 2, in <module>
ImportError: no module named 'btree'
>>> import esp32_ulp
>>> from esp32_ulp import src_to_binary
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'esp32_ulp.src_to_binary'
>>> 
```
are you running this code on another esp32 or directly on your computer ?

**Comment by Staars** [comment]
You can not `import esp32` when not using Micropython on an ESP32. For our use cases this is not needed. We only need a resulting binary.
The intended way is to use the template and put the own code into it. You do not have to enter the Micropython console. Just create „your“ script based on the template and launch `micropython yourscript.py`. I know, that this whole ULP-assembler thing is not exactly trivial.

**Comment by ouinouin** [comment]
yes , unfortunately even while launching from the console , micropythhon whines about the btree missing, i think its a compile issue.
its not trivial but its exciting because with enough examples or having a toolchain easy (like installing micropython if it works, it opens a lot of applications for tasmota. i  have not much  coding experience but motivation as a tester (i hope my next stop wont be some issues ecause i use it on an esp32C3.
i m actually trying to compile micropython instead of using the micropython from ubuntu , i ll let you know

**Comment by ouinouin** [comment]
@Staars  some progress here : had to compile micropython.... i followed this : 
https://github.com/micropython/micropython/tree/master/ports/unix

and got some result :

```
ouinouin@toshouin:~/soft/sources/micropython/ports/unix$ ./build-standard/micropython  /home/ouinouin/ulp_template.py
0001 my_var
0002 entry

#You can paste the following snippet into Tasmotas Berry console:
import ULP
ULP.wake_period(0,500000)
var c = bytes().fromb64("dWxwAAwADAAAAAAACAAAgAAAAAAAAACw")
ULP.load(c)
ULP.run()
ouinouin@toshouin:~/soft/sources/micropython/ports/unix$ 
```

also another detail worth to mention is in the compiled environment for unix, the upip package was not available, i had to use 
mip : 
launching micropython  in console mode then 
`>>> import mip
>>> mip.install("micropython-esp32-ulp")`

its not a great place to document that, but its a first start to tell people to not use micropython from debian repositories but to try to compile it (which adds another step for users not on ease, we should definitely add some "standard examples" to this to tackle the most current use case like : 
starting on an analog value threshold
starting on a rising or falling edge of a digital input 
thanks for your great job

**Comment by ouinouin** [comment]
i looked a bit for the esp32 C3 ,  the ulp coprocessor seems not the same as in the esp32 :  
https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-reference/system/ulp-risc-v.html
i dont know if the underlying code flatten those differences.
this is also a reson why i would upvote to have some wakeup by gpio  direct on the code of tasmota and not through ULP wich can change on each esp32 generation.

**Comment by Staars** [comment]
Well, you successfully have chosen the only currently available ESP32 platform without an ULP.
Slightly off-topic: I have been afraid, that Espressif will completely abandon the inclusion of ULPs when moving to RISCV for the main cores. But recently they announced an ULP for the upcoming C6.
First version - no ULP: https://www.espressif.com/en/news/ESP32_C6
New version - with ULP: https://www.espressif.com/en/products/socs/esp32-c6

But the C3 does not include an ULP.

**Comment by Staars** [comment]
For the S3 I already have a working ULP driver, which can be programmed in C, which is much easier.

**Comment by ouinouin** [comment]
> For the S3 I already have a working ULP driver, which can be programmed in C, which is much easier.

i ll check if the S3 is like the C3 but i doubt on it, since the architecture is different , but as you said as per the documentation of the C3, the ulp can be programmed in C.

**Comment by Staars** [comment]
As I guess you will use Tasmota then a S3 can do everything a C3 can do, but it has much more resources and thus can do „more“. It may be overkill for most applications and is of course pricier.
If you have a specific ULP use case in mind there is still the S2 to consider, which is cheaper than the S3 and does support the RiSCV-ULP too. I must admit, that I did not find the time to test it with my upcoming driver, but I would be really surprised, if it will not work.

**Comment by ouinouin** [comment]
@Staars : i firts try to reproduce your setup with an ESP32 pico contained in  the M5 atom lite.
i tried to translate the code of the blink example, just by changing in a dirty way the register to toggle the led with GPIO33 (GPIO2 is not there on the M5 atom lite.
i manage to make the led blink, so its a great success. but while sending the 
ULP.sleep(30) command, the led is no more blinking during the deepsleep time 
is there anything we have to do in the assembly program to enable ulp coprocessor during deepsleep, or is it the job of the ulp.sleep function ? 
or is it because i insanely adapted the pin numbering and there might be an issue with power domains or so ? 

here below i tried to match registers for gpio 33
```# constants from:
# https://github.com/espressif/esp-idf/blob/1cb31e5/components/soc/esp32/include/soc/soc.h 
#define DR_REG_RTCIO_BASE            0x3ff48400
# constants from:
# https://github.com/espressif/esp-idf/blob/1cb31e5/components/soc/esp32/include/soc/rtc_io_reg.h 
#define RTC_IO_TOUCH_PAD2_REG        (DR_REG_RTCIO_BASE + 0x8c)
#define RTC_IO_TOUCH_PAD2_MUX_SEL_M  (BIT(18))
#define RTC_GPIO_OUT_REG             (DR_REG_RTCIO_BASE + 0x0)
#define RTC_GPIO_ENABLE_REG          (DR_REG_RTCIO_BASE + 0xc)
#define RTC_GPIO_ENABLE_S            14
#define RTC_GPIO_OUT_DATA_S          14
# constants from:
# https://github.com/espressif/esp-idf/blob/1cb31e5/components/soc/esp32/include/soc/rtc_io_channel.h 
#define RTCIO_GPIO33_CHANNEL          8
# When accessed from the RTC module (ULP) GPIOs need to be addressed by their channel number
.set gpio, RTCIO_GPIO33_CHANNEL```

**Comment by Staars** [comment]
ULP.sleep() is correct. Hard to guess what went wrong here. Maybe it has something to do with power domain as you wrote.
I also read reports, that changing the ULP timer from within an ULP program can be unstable.

I will grab my ESP32 to check the deep sleep behavior of this blink example, but can not promise any time frame.

**Comment by ouinouin** [comment]
i got a nodemcu (like this i use the exact same pin number 2) board to be able to try by pasting directly the blink example as is on the tasmota docs :  (
> 

```#You can paste the following snippet into Tasmotas Berry console:
    import ULP
    ULP.wake_period(0,500000) # on time
    ULP.wake_period(1,200000) # off time 
    var c = bytes().fromb64("dWxwAAwAaAAAAAAADAAAgAAAAAAAAAAAEACAcgEAANDlryxyMABAgCcFzBkABWgdEACAcuGvjHIBAABoIQCAcgQAANASAIByCAAgcAQAAGgBAAWCWAAAgAQFaB0AAACSZAAAgAUFaB0BAACSZAAAgAAAALA=")
    ULP.load(c)
    ULP.run()
```
i got the exact same behavior, the ulp processor runs the code while esp32 is powered and as soon as I execute ULP.sleep(30) i get no more led blinking.
Edit : on the nodeMCU board, while the embedded led is blinking, i see a very very small blink on the led, it might be some config about internal resistors pull or something like that. to be continued

**Comment by Staars** [comment]
You maybe right about the pin setup.
On my test dev board of unknown source the blink example reduces the light intensity quite a lot in deep sleep, but continues with the blinking pattern. I never tested this example in deep sleep before. Interesting.
BTW, `restart 2` on the Tasmota console does not stop the blinking, so the ULP is obviously not stopped by it.

**Comment by Staars** [comment]
I adapted one of Espressifs examples to wake up from deep sleep by pressing a button on GPIO 0.
Debouncing seems not to work perfectly, but it should be at least a base for further improvement.
(I was to lazy to clean up the header, so there are some remnants from other examples in it)

```
#You can paste the following snippet into Tasmotas Berry console:
import ULP
ULP.wake_period(0,20000)
var io_num = ULP.gpio_init(0,0) # GPIO 0 to input 
var c = bytes().fromb64("dWxwAAwAzAAAABgAgwOAcg8AANA8AIBwEAAJggkBuC4wAMBwKAAAgAkB+C8PASByMADAcBAAQHIzA4ByDwAA0DMAAHAfAEByVABAgFMDgHJCA4ByDwAA0AsAAGgAAACwQwOAcg4AANAKAABycABAgBoAIHIOAABoAAAAsFMDgHJCA4ByDwAA0AsAAGgzA4ByDgAA0BoAAHIaAEByDgAAaGMDgHIOAADQGgAAcg4AAGhzA4ByDwAA0C8AIHC4AECAAAAAsDAAzCkQAEByuABAgAEAAJAAAACw")
ULP.load(c)
ULP.set_mem(55,3) #edge_count_to_wake_up
ULP.set_mem(56,io_num) #rtc_gpio_number
ULP.run()
```
